title: homelab-ez
description: A centralized documentation hub for my personal homelab, detailing the setup, configuration, and management of various self-hosted services.
theme: just-the-docs
color_scheme: "dark"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

url: https://rjhoppe.github.io/homelab-ez/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Define Jekyll collections
collections:
  infrastructure:
    permalink: "/:collection/:path/"
    output: true
  containers:
    permalink: "/:collection/:path/"
    output: true
  home-assistant:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    infrastructure:
      name: Infrastructure
      nav_fold: true
    containers:
      name: Containers
      nav_fold: true
    home-assistant:
      name: Home Assistant
      nav_fold: true
